name: DevCard

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 */3 * *"

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.3.1
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
          commit_branch: master
          commit_filename: devcard.png
          commit_message: "feat: update ${filename}"
